title: "Berna Altunisik"
email: berna.altunisik@gmail.com
timezone: UTC
baseurl: "https://bernaaltunisik.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Berna
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Berna
    display_name: Berna Altunisik
    avatar: 'assets/images/sal.png'
    email: berna.altunisik@gmail.com
    web: 
    twitter: 
    description: " "
# Social
social:
  linkedin: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
